[package]
name = "tilt-machine"
version = "0.1.0"
authors = ["Jacob Nesbitt <jjnesbitt2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serial = "0.4.0"
