# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ""

setup(
    long_description=readme,
    name="tiltmachine",
    version="0.1.0",
    python_requires="==3.*,>=3.7.0",
    author="Jacob Nesbitt",
    author_email="jjnesbitt2@gmail.com",
    packages=["tiltmachine"],
    package_dir={"": "."},
    package_data={},
    install_requires=["pyserial==3.*,>=3.4.0", "python-xlib==0.*,>=0.27.0"],
    extras_require={
        "dev": [
            "black==19.*,>=19.10.0.b0",
            "flake8==3.*,>=3.8.3",
            "flake8-black==0.*,>=0.2.1",
        ]
    },
)
